networks:
  r2r-network:
    external: 
      name: r2r_r2r-network  # Connect to existing r2r network

services:
  rag-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BASE_URL=http://r2r-r2r-1:7272  # Change this to the actual r2r service name
      - LOG_LEVEL=INFO
    volumes:
      - .:/app
      - ./logs:/app/logs
    networks:
      - r2r-network  # Add this to connect to r2r network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s